# Generated by Django 5.2.17 on 2026-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_completionsubmission_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionsubmission',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='completionsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
