# Generated by Django 5.2.17 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_completionsubmission_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
